# Generated by Django 5.2.7 on 2025-11-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0004_participant_meetup_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetup",
            name="participants",
            field=models.ManyToManyField(blank=True, to="meetups.participant"),
        ),
    ]
