# Generated by Django 5.2.7 on 2025-11-19 17:25

from django.db import migrations, models
import datetime



class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0005_alter_meetup_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="date",
            field=models.DateField(blank=True, default=datetime.date(2025, 11, 19)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetup",
            name="organizer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
