# Generated by Django 5.2.7 on 2025-11-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0006_meetup_date_meetup_organizer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetup",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
