# Generated by Django 5.2.7 on 2025-11-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0007_alter_meetup_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
