# Generated by Django 5.2.7 on 2025-11-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0008_meetup_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetup",
            name="time",
        ),
    ]
